name: sidebaranimationflutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  carousel_slider: ^1.4.1
  fluro: ^1.2.1
  firebase_database: ^3.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.1.1
  animated_text_kit: ^2.0.0
  fancy_on_boarding: ^1.5.0
  tuple: ^1.0.3
  google_fonts: ^0.3.2
  shared_preferences: ^0.5.6+3
  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  fluttertoast: ^3.1.3
  intro_slider: ^1.0.8

#  google_maps_flutter: ^0.5.19+2
  font_awesome_flutter: ^8.2.0
  location: ^2.3.5
  provider: ^3.1.0
  get: ^1.11.1
  auto_route: ^0.3.1
  flutter_google_places: ^0.2.3
  flutter_polyline_points: ^0.1.0
  get_it: ^1.0.3+2
  url_launcher: ^5.4.5
  flutter_spinkit: ^4.0.0
  flutter_android_lifecycle: ^1.0.0
  after_layout: ^1.0.7+2
  rect_getter: ^0.0.1
  gradient_text: ^1.0.2
  flutter_secure_storage: ^3.3.3
  bloc:
  flutter_mapbox_navigation: ^0.0.10
  equatable: ^0.6.1
  firebase_core: ^0.4.1+3
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  intl: ^0.16.1
  device_preview: ^0.4.4
  geolocator: ^5.1.4+2
  google_maps_webservice: ^0.0.16
  http: ^0.12.0+2
  cached_network_image: ^2.0.0-rc
  flutter_upi: ^0.0.2
  google_map_polyline: ^0.2.0+1
  google_maps_flutter: ^0.5.21+2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  numeric_keyboard: ^1.0.0
#  map_view:
#     git:
#        url: git://github.com/Eimji/flutter_google_map_view.git
#  camera: ^0.5.2+1
#  path_provider: ^1.1.0
#  path: ^1.6.2
#  esys_flutter_share: ^1.0.2
#  image_picker: 0.6.0+10
#  image_cropper: ^1.0.2
#  flutter_image_compress: ^0.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.3.2
  build_runner: ^1.8.0
  flutter_launcher_icons: ^0.7.4



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/font/
    - assets/fonts/
    - assets/images/
    - assets/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/Product_Sans_Bold.ttf
        - asset: assets/font/Product_Sans_Regular.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
